config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create, :show]
  end
    resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list_id), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to list_path(@list)
  end

private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>
<%= link_to "Back to List", list_path(@list) %>
</div>

app/views/bookmarks/show.html.erb
<%= @bookmark.movie.title %>
<%= @bookmark.comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1>LIST</h1>
<ol>
  <% @lists.each do |list|  %>
  <li><%= link_to list.name, list_path(list)%></li>
  <% end %>
</ol>
<%= link_to "create new list", new_list_path %>
</div>

app/views/lists/new.html.erb
<div class="container">
<h1>Create a New List</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.button :submit, class: "btn btn-primary"%>
  <% end %>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<div class="container"></div>
<ul>
<% @list.bookmarks.each do |bookmark| %>
<li><%= link_to bookmark.movie.title, list_bookmark_path(@list) %></li>
<%= link_to "Remove", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

<%end %>
</ul>
</div>

<br>

<%= link_to "Back to List", lists_path %>
<%= link_to "Add to List", new_list_bookmark_path(@list) %>